contents:
  - {directory: ARmodeling, name: ARモデリングツール, date: 2012/9, url: "https://www.youtube.com/watch?v=pb9ExH-FXCY"}
  - {directory: Hako, name: Hako, date: 2012/11, url: "https://www.youtube.com/watch?v=ZBfd_9pjG98"}
  - {directory: duelDisk, name: デュエルディスク, date: 2013/5}
  - {directory: ProjectronMapping, name: Projectron Mapping, date: 2013/10-2014/12}
  - {directory: numericKeypad, name: オリジナルテンキー, date: 2014/3, url: "https://sites.google.com/view/gutugutu3030/other/tenkiwojietishitegaizaosuru" }
  - {directory: somen, name: 流しそうめん音ゲー, date: 2014/9 }
  - {directory: realtimeProcessing, name: Processing RealtimeMode, date: 2015/3 }
  - {directory: gestureProcessing, name: Gesture Processing, date: 2015/9, url: "https://www.youtube.com/watch?v=3zLj8GU9hfM" }
  - {directory: DraggableBoard, name: ドラッグで配線できる基板, date: 2015/12 }
  - {directory: pinteraction, name: pinteraction, date: 2015/9-2016/3 }
  - {directory: GPrint, name: Processing コンソールサーチモード, date: 2016/1, url: "https://github.com/gutugutu3030/gprintMode" }
  - {directory: 8mmFilm, name: 自作8mmフィルムプロジェクト, date: 2016/5 }
  - {directory: kirbyPC, name: カービィでPC作ってみた, date: 2016/7 }
  - {directory: Fitter, name: Fitter, date: 2016/7-2018/3 }
  - {directory: Gilgamesh, name: やさしいギルガメッシュ, date: 2016/9 }
  - {directory: PUI3DPrinter, name: Pocon, date: 2016/7-2018/3 }
  - {directory: PaperBattler, name: Paper Battler, date: 2017/1 }
  - {directory: 8mmFilm.projector, name: ミニミニ8mm映写機, date: 2017/1 }
  - {directory: Theater, name: Theater, date: 2017/1-2017/2 }
  - {directory: mobileFabrication, name: 背負型3Dプリンタ, date: 2017/3-2018/3, url: "https://sites.google.com/view/gutugutu3030/quanku-guan-xinai/3dpurintawobeifuttehuajianshitahua" }
  - {directory: 8mmFilm.game, name: ICレスゲーム機, date: 2017/9 }
  - {directory: 3DPrinCar, name: 3DPrinCar, date: 2017/5-2018/1 }
  - {directory: reallive2d, name: MultiplaneGirl, date: 2018/6-2022 }

career:
  - {date: 2012/4, description: "明治大学理工学部情報科学科入学"}
  - {date: 2015/7, description: "玉木研所属"}
  - {date: 2016/3, description: "明治大学理工学部情報科学科卒業"}
  - {date: 2016/4, description: "明治大学大学院理工学研究科新領域創造専攻入学（宮下研）"}
  - {date: 2017/7/24, description: "Zing!にて「3Dプリンタで“声の立体化”に挑戦!?」記事掲載", url: "http://eonet.jp/zing/articles/_4100703.html"}
  - {date: 2017/9/6, description: "新たな技術を福祉にいかす体験ワークショップにて研究事例紹介", url: "http://goodjobcenter.com/topics/report/959/"}
  - {date: 2017/9/22, description: "Zing!にてまるでハンドパワー！「手をかざすと動く台」をFabってみた」記事掲載", url: "http://eonet.jp/zing/articles/_4101119.html"}
  - {date: 2018/3, description: "明治大学大学院理工学研究科新領域創造専攻卒業・工学（修士）取得"}
  - {date: 2018/4, description: "チームラボ株式会社入社"}
  - {date: 2022~, description: "インタラクティブシステムとソフトウェアに関するワークショップ(WISS)にてプログラム委員に就任", url: "https://www.wiss.org/"}

qualification:
  - 普通自動車第一種運転免許（AT限定）
  - 第二種電気工事士
  - Silver SE 17

htmlCreator:
  - !!gutugutu3030.config.html_creator.IndexHtmlCreator
    path: index.pebl
  - !!gutugutu3030.config.html_creator.ProfileHtmlCreator
    path: profile.pebl
  - !!gutugutu3030.config.html_creator.RootHtmlCreator
    path: root/
  - !!gutugutu3030.config.html_creator.ContentsHtmlCreator
    path: contents/
  - !!gutugutu3030.config.html_creator.StarHtmlCreator
    path: star.pebl
    thumbnailImagePath: star/small/
    fullsizeImagePath: star/full/
    video:
      "2023-07-22,ホーリーグレイル　習作.jpg" : "https://www.youtube.com/embed/1YQO81ByZ8k"
      "2022-12-13,はやま湖.jpg" : "https://www.youtube.com/embed/kqlHLPIOVQE"
      "2024-01-01,常しえの夜空.jpg" : "https://www.youtube.com/embed/vp9j_aEFtkw"
  