/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.pebbletemplates.pebble.PebbleEngine;
import io.pebbletemplates.pebble.template.PebbleTemplate;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashMap;

public class App {
  public static void main(String[] args) throws IOException {
    PebbleEngine engine = new PebbleEngine.Builder().build();
    createRootHtml(engine);
  }

  private static void createRootHtml(PebbleEngine engine) throws IOException {
    Files.list(Paths.get("src/main/resources/root"))
        .filter(Files::isRegularFile)
        .filter(path -> path.toString().endsWith(".html"))
        .forEach(
            path -> {
              PebbleTemplate compiledTemplate = engine.getTemplate("root/" + path.getFileName());
              try (FileWriter writer = new FileWriter("../../" + path.getFileName())) {
                compiledTemplate.evaluate(writer, new HashMap<>());
              } catch (IOException e) {
                e.printStackTrace();
              }
            });
  }
}
