/*
 * This source file was generated by the Gradle 'init' task
 */
package gutugutu3030;

import gutugutu3030.config.WebConfig;
import io.pebbletemplates.pebble.PebbleEngine;
import java.io.IOException;
import org.yaml.snakeyaml.LoaderOptions;
import org.yaml.snakeyaml.Yaml;

public class App {
  public static void main(String[] args) throws IOException {
    LoaderOptions loaderOptions = new LoaderOptions();
    loaderOptions.setTagInspector(tag -> true);
    Yaml yaml = new Yaml(loaderOptions);

    final var config =
        yaml.loadAs(ClassLoader.getSystemResourceAsStream("config.yaml"), WebConfig.class);
    System.out.println(config);

    final PebbleEngine engine = new PebbleEngine.Builder().build();
    config.htmlCreator.forEach(
        creator -> {
          try {
            creator.create(engine, config);
          } catch (IOException e) {
            e.printStackTrace();
          }
        });
  }
}
